### ISSUE TITLE
CAn you please help me fix this

### ISSUE THREAD

**Issue by justinjean111** [Meetmetha/tiktokphpdownloader#1]
It works with url from PC but links from phone like that start with vm.tiktok.com like this link https://vm.tiktok.com/ZMRqBxMsV/
it does not work on it
I spend two days trying to fix this issue but I didnt
can you please help me

**Comment by Meetmetha** [comment]
Connect with me via email miteshmehta2018@gmail.com I will give you way to download these video urls with & without Watermark

**Comment by Meetmetha** [comment]
For Issue created here just get the id from url and pass it to function refer line 208
